import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('Dify tool Agent paper smoke script', () => {
  it('runs a real paper-context smoke against the autonomous Tool Agent', () => {
    const script = readFileSync(resolve('scripts/smoke-dify-tool-agent-paper.mjs'), 'utf8')
    const benchmark = readFileSync(resolve('scripts/benchmark-dify-tool-agent.mjs'), 'utf8')
    const packageJson = readFileSync(resolve('package.json'), 'utf8')
    const runbook = readFileSync(resolve('docs/mvp-runbook.md'), 'utf8')

    expect(script).toContain('ResearchNotion Tool Agent')
    expect(script).toContain('paper_demo_2017_attention_is_all_you_need_pdf')
    expect(script).toContain('/internal/reading-state')
    expect(script).toContain('scripts/deepseek-bridge.mjs')
    expect(script).toContain('cmd.exe')
    expect(script).toContain('pnpm dev')
    expect(script).toContain("['scripts/use-deepseek-endpoint.mjs', 'bridge']")
    expect(script).toContain('get_current_context')
    expect(script).toContain('get_paper_outline')
    expect(script).toContain('get_current_page_text')
    expect(script).toContain('investigate_paper')
    expect(script).toContain('hasBroadEvidenceTool')
    expect(script).toContain('message_end')
    expect(script).toContain('Tool Agent paper smoke passed')
    expect(script).toContain('toolServiceHeaders')
    expect(packageJson).toContain('smoke:dify-agent-paper')
    expect(runbook).toContain('pnpm smoke:dify-agent-paper')
    expect(benchmark).toContain("id: 'outline'")
    expect(benchmark).toContain("id: 'full-paper'")
    expect(benchmark).toContain("id: 'library'")
    expect(benchmark).toContain("id: 'comparison'")
    expect(benchmark).toContain('requiredEvidencePaperIds')
    expect(benchmark).toContain('evidenceCoveragePass')
    expect(benchmark).toContain('/internal/tool-invocations')
    expect(benchmark).toContain("id: 'follow-up'")
    expect(benchmark).toContain("id: 'experiment-evidence'")
    expect(benchmark).toContain("id: 'limitations'")
    expect(benchmark).toContain("id: 'bilingual-comparison'")
    expect(benchmark).toContain("id: 'compound-aspects'")
    expect(benchmark).toContain("id: 'corrected-reference'")
    expect(benchmark).toContain("id: 'claim-audit'")
    expect(benchmark).toContain('investigate_library')
    expect(benchmark).toContain('aspectCount')
    expect(benchmark).toContain('usesBalancedEvidence')
    expect(benchmark).toContain('followUpQuery')
    expect(benchmark).toContain('conversation_id: conversationId')
    expect(benchmark).toContain("scope: 'folder'")
    expect(benchmark).toContain("benchmarkCase.scope === 'paper' ? attentionPaperId : null")
    expect(packageJson).toContain('benchmark:dify-agent')
  })
})
